fastlane_version "1.109.0"
default_platform :ios

lane :beta do
    increment_build_number
    cocoapods
    cert(username: ENV["username"])
    sigh(username: ENV["username"], app_identifier: ENV["app_identifier"])
    gym(scheme: ENV["scheme"])
    crashlytics(api_token: ENV["api_token"], build_secret: ENV["build_secret"])
end
